# -----------------------------
# Delta Lake
# -----------------------------
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog

# -----------------------------
# Unity Catalog
# -----------------------------
spark.sql.catalog.uc=io.unitycatalog.spark.UCSingleCatalog
spark.sql.defaultCatalog=uc
# Set at runtime:
# spark.sql.catalog.uc.uri=thrift://unity-catalog:9083
