
# =========================
# Named Volumes
# =========================
volumes:
  uc-pgdata:
  neo4jdata:
  grafanadata:
  unitycatalog_data:
  miniodata: 

# =========================
# Network
# =========================
networks:
  discogs-net:
    driver: bridge


services:

  # =========================
  # Unity Catalog
  # =========================
  uc-server:
    build:
      context: ./docker/unitycatalog
      dockerfile: Dockerfile
    container_name: uc-server
    hostname: uc-server
    ports:
      - "8081:8080"   # host 8081 → container 8080
    volumes:
      - ./config/unitycatalog/etc/conf:/home/unitycatalog/etc/conf
    networks:
      - discogs-net
    environment:
      UNITYCATALOG_TOKEN: test-token
      AWS_REGION: us-east-1
      # These tell UC's S3 client to use MinIO
      UC_S3_ENDPOINT: http://minio:9000
      UC_S3_PATH_STYLE_ACCESS: "true"

      UC_DB_HOST: uc-postgres
      UC_DB_PORT: 5432
      UC_DB_NAME: unitycatalog
      UC_DB_USER: uc
      UC_DB_PASSWORD: ucpassword
      SPRING_DATASOURCE_URL: jdbc:postgresql://uc-postgres:5432/unitycatalog
      SPRING_DATASOURCE_USERNAME: uc
      SPRING_DATASOURCE_PASSWORD: ucpassword
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      uc-postgres:
        condition: service_healthy


  uc-postgres:
    image: postgres:17
    container_name: uc-postgres
    environment:
      POSTGRES_USER: uc
      POSTGRES_PASSWORD: ucpassword
      POSTGRES_DB: unitycatalog
    volumes:
      - ./data/unitycatalog-pg:/var/lib/postgresql/data
    networks:
      - discogs-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uc -d unitycatalog"]
      interval: 5s
      timeout: 5s
      retries: 10



  uc-ui:
    build:
      context: ./docker/unitycatalog-ui
      dockerfile: Dockerfile
    container_name: uc-ui
    ports:
      - "8082:3000"   # host 8082 → container 3000
    depends_on:
      - uc-server
    networks:
      - discogs-net
    environment:
      REACT_APP_API_URL: http://uc-server:8080


  minio:
    image: minio/minio:latest
    container_name: uc-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    networks:
      - discogs-net




  # =========================
  # Spark Standalone Cluster
  # =========================

  spark-master:
    build: ./docker/spark
    image: my-spark:latest
    container_name: spark-master
    hostname: spark-master
    command: >
      bash -c "
        /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master & jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
      "
    ports:
      - "7077:7077"   # Spark master cluster port
      - "8083:8080"   # Spark UI
      - "8888:8888"   # Jupyter Lab
    volumes:
      - ./debug:/opt/spark/work-dir
      - ./app:/app
      - ./logs:/logs
      - ./data:/data
      - ./metadata:/metadata
      - ./data_tests:/data_tests
      - ./config:/config
    networks:
      - discogs-net
    env_file: ".env"
    environment:
      - SPARK_CONF_DIR=/config
    depends_on:
      - uc-server
      - minio

  spark-worker:
    build: ./docker/spark
    image: my-spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    environment:
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 2g
      SPARK_CONF_DIR: /config
      
    volumes:
      - ./debug:/opt/spark/work-dir
      - ./app:/app
      - ./logs:/logs
      - ./data:/data
      - ./metadata:/metadata
      - ./data_tests:/data_tests
      - ./config:/config
    networks:
      - discogs-net
    env_file: ".env"

#
#  # =========================
#  # PostgreSQL (Data Warehouse)
#  # =========================
#  postgres:
#    image: postgres:16
#    container_name: postgres
#    environment:
#      POSTGRES_USER: discogs
#      POSTGRES_PASSWORD: discogs
#      POSTGRES_DB: discogs_dw
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    networks:
#      - discogs-net
#
#  # =========================
#  # dbt (Postgres Transformations)
#  # =========================
#  dbt:
#    image: ghcr.io/dbt-labs/dbt-postgres:1.7.0
#    container_name: dbt
#    depends_on:
#      - postgres
#    volumes:
#      - ./dbt:/usr/app
#    working_dir: /usr/app
#    command: dbt run
#    networks:
#      - discogs-net
#
#  # =========================
#  # Airflow (Optional Orchestration)
#  # =========================
#  airflow:
#    build: ./docker/airflow
#    container_name: airflow
#    command: airflow standalone
#    depends_on:
#      - spark-master
#      - postgres
#    ports:
#      - "8084:8080"   # Host 8084 → Airflow UI
#    environment:
#      AIRFLOW__CORE__EXECUTOR: LocalExecutor
#      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
#    volumes:
#      - ./airflow/dags:/opt/airflow/dags
#      - ./airflow/logs:/opt/airflow/logs
#      - ./app:/app
#      - ./data:/data
#    networks:
#      - discogs-net
#
#  # =========================
#  # Neo4j (Graph Analytics / Portfolio Graph)
#  # =========================
#  neo4j:
#    image: neo4j:5
#    container_name: neo4j
#    environment:
#      NEO4J_AUTH: neo4j/discogs
#    ports:
#      - "7474:7474"   # Browser UI
#      - "7687:7687"   # Bolt protocol
#    volumes:
#      - neo4jdata:/data
#    networks:
#      - discogs-net
#
#  # =========================
#  # Dash (User-Facing App)
#  # =========================
#  dash:
#    build: ./dash
#    container_name: dash
#    depends_on:
#      - postgres
#    ports:
#      - "8050:8050"
#    networks:
#      - discogs-net
#
#  # =========================
#  # Prometheus (Monitoring)
#  # =========================
#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - discogs-net
#
#  # =========================
#  # Grafana (Monitoring Dashboard)
#  # =========================
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    depends_on:
#      - prometheus
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafanadata:/var/lib/grafana
#    networks:
#      - discogs-net
#
