rm /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/logs/discogs_*
rm -rf "/home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/metrics/bronze"
rm -rf "/home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/bronze"
rm -rf "/home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/silver"

rm /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/raw/discogs_*.gz


cp /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests_bak/raw/discogs_20251101_artists_sample_100000.xml.gz /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/raw/discogs_20251101_artists_sample_100000.xml.gz

cp /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests_bak/raw/discogs_20251101_releases_sample_100000.xml.gz /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/raw/discogs_20251101_releases_sample_100000.xml.gz
docker exec spark-master python3 /jobs/bronze_ingest.py

cp /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests_bak/raw/discogs_20251201_artists_sample_200000.xml.gz /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/raw/discogs_20251201_artists_sample_200000.xml.gz

cp /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests_bak/raw/discogs_20251101_releases_sample_100000.xml.gz /home/nicolas/github_nicolascalo/six_degrees_of_kevin_bacon_but_for_music/data_tests/raw/discogs_20251101_releases_sample_100000.xml.gz
docker exec spark-master python3 /jobs/bronze_ingest.py