hibernate.connection.url=jdbc:postgresql://uc-postgres:5432/unitycatalog
hibernate.connection.username=uc
hibernate.connection.password=ucpass
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update